ALTER TABLE global_command_intelligence_write_workflow_events
  DROP CONSTRAINT IF EXISTS gci_write_event_type_allowed;

ALTER TABLE global_command_intelligence_write_workflow_events
  ADD CONSTRAINT gci_write_event_type_allowed CHECK (event_type IN (
    'patient.created',
    'patient.updated',
    'clinical.file.ingested',
    'clinical.file.extracted',
    'clinical.file.analyzed',
    'clinical.patient.chat.logged',
    'clinical.global.chat.logged',
    'clinical.reasoning.completed',
    'clinical.report.analyzed',
    'clinical.report.translated',
    'clinical.workflow.advanced',
    'clinical.notification.sent',
    'encounter.created',
    'clinical.note.created',
    'allergy.created',
    'condition.created',
    'medication.created',
    'vital.signs.created',
    'care.team.updated',
    'lab.order.created',
    'specimen.collected',
    'specimen.received',
    'lab.result.entered',
    'lab.result.validated',
    'lab.result.approved',
    'critical.lab.result.flagged',
    'imaging.order.created',
    'imaging.study.started',
    'imaging.study.completed',
    'radiology.report.created',
    'radiology.report.approved',
    'critical.finding.flagged',
    'prescription.created',
    'prescription.approval.requested',
    'prescription.doctor.approved',
    'prescription.reviewed',
    'medication.safety.validated',
    'medication.dispensed',
    'pharmacy.inventory.updated',
    'medication.safety.alert.flagged',
    'pharmacy.safety.checked',
    'appointment.created',
    'appointment.updated',
    'appointment.cancelled',
    'appointment.checked_in',
    'appointment.completed',
    'treatment.order.requested',
    'treatment.order.doctor.approved',
    'user.created',
    'user.updated',
    'role.assigned',
    'role.created',
    'tenant.created',
    'organization.created',
    'department.created',
    'configuration.updated',
    'patient.appointment.requested',
    'patient.secure.message.sent',
    'patient.refill.requested',
    'patient.report.requested',
    'patient.communication.preferences.updated'
  ));

INSERT INTO global_command_intelligence_migrations (version)
VALUES ('005_operational_core_write_events')
ON CONFLICT (version) DO NOTHING;
